### ISSUE TITLE
Live stream support?

### ISSUE THREAD

**Issue by danya02** [DvorakDwarf/Infinite-Storage-Glitch#24]
A way to encode data into video doesn't need to be used only for storing data; you can also use this for transferring data.

If you encode the frames into a live stream, instead of a file, then you're broadcasting the contents of that file over the live stream.
This could be useful for sending files that you don't need to keep permanent record of, or if you want to control when the file can be acquired.

The sender program would create frames, which are sent to a live video ingest server, and then rebroadcast to receiver clients, which connect to the livestream in order to download the file.

In order to deal with compression issues, which are even more severe in livestreams, a back channel (for example using chat) is needed. Receivers would say in chat when they've missed a piece of the data, and the sender would aggregate this info in order to decide what frames to send next -- for example, should it continue sending the next part of the file, or retransmit the previous one to make sure everyone received it; or, should it decrease the information density of the video to minimize losses, or increase it when the clients are receiving it well. In addition, the different clients could talk to each other in the chat, for example telling each other about the pieces they have and repeating them if someone missed them.

This requires a very big refactor to break apart the functionality of producing frames, encoding them, and saving them into separate pieces of code. In addition, whenever peer-to-peer communication is involved, everything gets much more complicated. For this reason, this is a low-priority task for now.

**Comment by rpadaki** [comment]
Instead of using the chat, you can use [fountain codes](https://en.wikipedia.org/wiki/Fountain_code) to generate frames from your source data.

The main idea is to produce a (potentially infinite) sequence of frames such that if you receive at least N frames, you are able to reconstruct the original message, for N at least as large as the number of frames in the initial encoding (if not always, then maybe with a high probability).

In the case of [Raptor codes](https://en.wikipedia.org/wiki/Raptor_code), for example, data consisting of k original frames can be recovered:
- by receiving any k of the livestream frames with >99% probability
- by receiving any k+2 of the livestream frames with >99.9999 probability
So as you watch the livestream for longer and longer, you have an exceedingly high probability of recovering the source data, even if you are dropping many of the frames!
